[package]
name = "marlowe_lang"
description = "experimental parser lib for Cardano Marlowe DSL"
version = "0.1.1"
edition = "2021"
authors = ["Olof Blomqvist <olof@twnet.se>"]
repository = "https://github.com/OlofBlomqvist/marlowe_rust"
license-file = "licence"

[dependencies]
pest_derive = "2.1.0"
decurse = "0.0.4"
pest = { version = "2.1.3", features= ["pretty-print"] }
serde = "1.0.137"
serde_json ="1.0.81"
clap = { version = "3.1.18", features = ["derive"] }


[lib]
name = "marlowe_lang"
path = "src/lib/lib.rs"

[[bin]]
name = "marlowe_lang_cli"
path = "src/cli_tool_bin/main.rs"